// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamFive.DataStorage;

#nullable disable

namespace TeamFive.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231028160208_InitMigration")]
    partial class InitMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TeamFive.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            InstrumentId = 1,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4535),
                            Family = "Keyboard",
                            Name = "Piano",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4537)
                        },
                        new
                        {
                            InstrumentId = 2,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4715),
                            Family = "String",
                            Name = "Guitar",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4715)
                        },
                        new
                        {
                            InstrumentId = 3,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4732),
                            Family = "Woodwind",
                            Name = "Flute",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4732)
                        },
                        new
                        {
                            InstrumentId = 4,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4758),
                            Family = "Percussion",
                            Name = "Drums",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4758)
                        },
                        new
                        {
                            InstrumentId = 5,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4784),
                            Family = "String",
                            Name = "Violin",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4784)
                        },
                        new
                        {
                            InstrumentId = 6,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4803),
                            Family = "Brass",
                            Name = "Trumpet",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4804)
                        },
                        new
                        {
                            InstrumentId = 7,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4824),
                            Family = "Woodwind",
                            Name = "Saxophone",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4824)
                        },
                        new
                        {
                            InstrumentId = 8,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4941),
                            Family = "String",
                            Name = "Bass Guitar",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4941)
                        },
                        new
                        {
                            InstrumentId = 9,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4963),
                            Family = "Woodwind",
                            Name = "Clarinet",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(4963)
                        },
                        new
                        {
                            InstrumentId = 11,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5000),
                            Family = "Brass",
                            Name = "Trombone",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5001)
                        },
                        new
                        {
                            InstrumentId = 12,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5017),
                            Family = "String",
                            Name = "Harp",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5018)
                        },
                        new
                        {
                            InstrumentId = 13,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5030),
                            Family = "Percussion",
                            Name = "Vibrophone",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5030)
                        },
                        new
                        {
                            InstrumentId = 14,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5047),
                            Family = "Woodwind",
                            Name = "Oboe",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5047)
                        },
                        new
                        {
                            InstrumentId = 15,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5058),
                            Family = "Woodwind",
                            Name = "Bassoon",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5059)
                        },
                        new
                        {
                            InstrumentId = 17,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5077),
                            Family = "String",
                            Name = "Classical Guitar",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5077)
                        },
                        new
                        {
                            InstrumentId = 18,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5106),
                            Family = "Brass",
                            Name = "French Horn",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5106)
                        },
                        new
                        {
                            InstrumentId = 19,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5119),
                            Family = "Keyboard",
                            Name = "Accordion",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5120)
                        },
                        new
                        {
                            InstrumentId = 20,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5133),
                            Family = "String",
                            Name = "Cello",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 691, DateTimeKind.Utc).AddTicks(5133)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LessonId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("TeamFive.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TeamFive.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 760, DateTimeKind.Utc).AddTicks(3033),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 760, DateTimeKind.Utc).AddTicks(3037),
                            UserId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 830, DateTimeKind.Utc).AddTicks(4395),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 830, DateTimeKind.Utc).AddTicks(4401),
                            UserId = 2
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 900, DateTimeKind.Utc).AddTicks(7899),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 900, DateTimeKind.Utc).AddTicks(7902),
                            UserId = 3
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 971, DateTimeKind.Utc).AddTicks(5454),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 971, DateTimeKind.Utc).AddTicks(5460),
                            UserId = 4
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 42, DateTimeKind.Utc).AddTicks(5141),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 42, DateTimeKind.Utc).AddTicks(5147),
                            UserId = 5
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 113, DateTimeKind.Utc).AddTicks(3823),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 113, DateTimeKind.Utc).AddTicks(3831),
                            UserId = 6
                        },
                        new
                        {
                            RoleId = 7,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 183, DateTimeKind.Utc).AddTicks(2447),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 183, DateTimeKind.Utc).AddTicks(2450),
                            UserId = 7
                        },
                        new
                        {
                            RoleId = 8,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 253, DateTimeKind.Utc).AddTicks(3690),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 253, DateTimeKind.Utc).AddTicks(3693),
                            UserId = 8
                        },
                        new
                        {
                            RoleId = 9,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 323, DateTimeKind.Utc).AddTicks(7651),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 323, DateTimeKind.Utc).AddTicks(7656),
                            UserId = 9
                        },
                        new
                        {
                            RoleId = 10,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 394, DateTimeKind.Utc).AddTicks(7556),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 394, DateTimeKind.Utc).AddTicks(7561),
                            UserId = 10
                        },
                        new
                        {
                            RoleId = 11,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 465, DateTimeKind.Utc).AddTicks(4695),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 465, DateTimeKind.Utc).AddTicks(4699),
                            UserId = 11
                        },
                        new
                        {
                            RoleId = 12,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 534, DateTimeKind.Utc).AddTicks(7738),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 534, DateTimeKind.Utc).AddTicks(7743),
                            UserId = 12
                        },
                        new
                        {
                            RoleId = 13,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 604, DateTimeKind.Utc).AddTicks(5582),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 604, DateTimeKind.Utc).AddTicks(5587),
                            UserId = 13
                        },
                        new
                        {
                            RoleId = 14,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 674, DateTimeKind.Utc).AddTicks(2155),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 674, DateTimeKind.Utc).AddTicks(2159),
                            UserId = 14
                        },
                        new
                        {
                            RoleId = 15,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 744, DateTimeKind.Utc).AddTicks(4105),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 744, DateTimeKind.Utc).AddTicks(4109),
                            UserId = 15
                        },
                        new
                        {
                            RoleId = 16,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 814, DateTimeKind.Utc).AddTicks(8637),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 814, DateTimeKind.Utc).AddTicks(8641),
                            UserId = 16
                        },
                        new
                        {
                            RoleId = 17,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 887, DateTimeKind.Utc).AddTicks(2151),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 887, DateTimeKind.Utc).AddTicks(2156),
                            UserId = 17
                        },
                        new
                        {
                            RoleId = 18,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 956, DateTimeKind.Utc).AddTicks(9744),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 956, DateTimeKind.Utc).AddTicks(9749),
                            UserId = 18
                        },
                        new
                        {
                            RoleId = 19,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 28, DateTimeKind.Utc).AddTicks(2261),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 28, DateTimeKind.Utc).AddTicks(2266),
                            UserId = 19
                        },
                        new
                        {
                            RoleId = 20,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 96, DateTimeKind.Utc).AddTicks(4893),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 96, DateTimeKind.Utc).AddTicks(4898),
                            UserId = 20
                        },
                        new
                        {
                            RoleId = 21,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 167, DateTimeKind.Utc).AddTicks(3133),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 167, DateTimeKind.Utc).AddTicks(3141),
                            UserId = 21
                        },
                        new
                        {
                            RoleId = 22,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 236, DateTimeKind.Utc).AddTicks(5136),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 236, DateTimeKind.Utc).AddTicks(5141),
                            UserId = 22
                        },
                        new
                        {
                            RoleId = 23,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 306, DateTimeKind.Utc).AddTicks(4498),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 306, DateTimeKind.Utc).AddTicks(4503),
                            UserId = 23
                        },
                        new
                        {
                            RoleId = 24,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 375, DateTimeKind.Utc).AddTicks(9109),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 375, DateTimeKind.Utc).AddTicks(9113),
                            UserId = 24
                        },
                        new
                        {
                            RoleId = 25,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 445, DateTimeKind.Utc).AddTicks(5399),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 445, DateTimeKind.Utc).AddTicks(5405),
                            UserId = 25
                        },
                        new
                        {
                            RoleId = 26,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 514, DateTimeKind.Utc).AddTicks(2769),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 514, DateTimeKind.Utc).AddTicks(2776),
                            UserId = 26
                        },
                        new
                        {
                            RoleId = 27,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 584, DateTimeKind.Utc).AddTicks(5232),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 584, DateTimeKind.Utc).AddTicks(5237),
                            UserId = 27
                        },
                        new
                        {
                            RoleId = 28,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 654, DateTimeKind.Utc).AddTicks(5382),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 654, DateTimeKind.Utc).AddTicks(5387),
                            UserId = 28
                        },
                        new
                        {
                            RoleId = 29,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 724, DateTimeKind.Utc).AddTicks(3166),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 724, DateTimeKind.Utc).AddTicks(3171),
                            UserId = 29
                        },
                        new
                        {
                            RoleId = 30,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 793, DateTimeKind.Utc).AddTicks(1707),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 793, DateTimeKind.Utc).AddTicks(1713),
                            UserId = 30
                        },
                        new
                        {
                            RoleId = 31,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 863, DateTimeKind.Utc).AddTicks(2409),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 863, DateTimeKind.Utc).AddTicks(2414),
                            UserId = 31
                        },
                        new
                        {
                            RoleId = 32,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 933, DateTimeKind.Utc).AddTicks(3727),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 933, DateTimeKind.Utc).AddTicks(3732),
                            UserId = 32
                        },
                        new
                        {
                            RoleId = 33,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 3, DateTimeKind.Utc).AddTicks(6662),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 3, DateTimeKind.Utc).AddTicks(6667),
                            UserId = 33
                        },
                        new
                        {
                            RoleId = 34,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 73, DateTimeKind.Utc).AddTicks(7096),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 73, DateTimeKind.Utc).AddTicks(7101),
                            UserId = 34
                        },
                        new
                        {
                            RoleId = 35,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 143, DateTimeKind.Utc).AddTicks(6724),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 143, DateTimeKind.Utc).AddTicks(6729),
                            UserId = 35
                        },
                        new
                        {
                            RoleId = 36,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 213, DateTimeKind.Utc).AddTicks(2931),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 213, DateTimeKind.Utc).AddTicks(2937),
                            UserId = 36
                        },
                        new
                        {
                            RoleId = 37,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 282, DateTimeKind.Utc).AddTicks(8362),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 282, DateTimeKind.Utc).AddTicks(8367),
                            UserId = 37
                        },
                        new
                        {
                            RoleId = 38,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 352, DateTimeKind.Utc).AddTicks(8585),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 352, DateTimeKind.Utc).AddTicks(8590),
                            UserId = 38
                        },
                        new
                        {
                            RoleId = 39,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 422, DateTimeKind.Utc).AddTicks(725),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 422, DateTimeKind.Utc).AddTicks(729),
                            UserId = 39
                        },
                        new
                        {
                            RoleId = 40,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 491, DateTimeKind.Utc).AddTicks(4459),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 491, DateTimeKind.Utc).AddTicks(4465),
                            UserId = 40
                        },
                        new
                        {
                            RoleId = 41,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 561, DateTimeKind.Utc).AddTicks(6126),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 561, DateTimeKind.Utc).AddTicks(6213),
                            UserId = 41
                        },
                        new
                        {
                            RoleId = 42,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 631, DateTimeKind.Utc).AddTicks(2929),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 631, DateTimeKind.Utc).AddTicks(2935),
                            UserId = 42
                        },
                        new
                        {
                            RoleId = 43,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 701, DateTimeKind.Utc).AddTicks(2871),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 701, DateTimeKind.Utc).AddTicks(2876),
                            UserId = 43
                        },
                        new
                        {
                            RoleId = 44,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 770, DateTimeKind.Utc).AddTicks(6163),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 770, DateTimeKind.Utc).AddTicks(6169),
                            UserId = 44
                        },
                        new
                        {
                            RoleId = 45,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 840, DateTimeKind.Utc).AddTicks(7209),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 840, DateTimeKind.Utc).AddTicks(7214),
                            UserId = 45
                        },
                        new
                        {
                            RoleId = 46,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 910, DateTimeKind.Utc).AddTicks(5750),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 910, DateTimeKind.Utc).AddTicks(5755),
                            UserId = 46
                        },
                        new
                        {
                            RoleId = 47,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 980, DateTimeKind.Utc).AddTicks(8674),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 980, DateTimeKind.Utc).AddTicks(8680),
                            UserId = 47
                        },
                        new
                        {
                            RoleId = 48,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 49, DateTimeKind.Utc).AddTicks(5431),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 49, DateTimeKind.Utc).AddTicks(5436),
                            UserId = 48
                        },
                        new
                        {
                            RoleId = 49,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 118, DateTimeKind.Utc).AddTicks(6514),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 118, DateTimeKind.Utc).AddTicks(6518),
                            UserId = 49
                        },
                        new
                        {
                            RoleId = 50,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 188, DateTimeKind.Utc).AddTicks(9934),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 188, DateTimeKind.Utc).AddTicks(9939),
                            UserId = 50
                        },
                        new
                        {
                            RoleId = 51,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 258, DateTimeKind.Utc).AddTicks(5451),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 258, DateTimeKind.Utc).AddTicks(5459),
                            UserId = 51
                        },
                        new
                        {
                            RoleId = 52,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 329, DateTimeKind.Utc).AddTicks(136),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 329, DateTimeKind.Utc).AddTicks(144),
                            UserId = 52
                        },
                        new
                        {
                            RoleId = 53,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 398, DateTimeKind.Utc).AddTicks(2549),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 398, DateTimeKind.Utc).AddTicks(2553),
                            UserId = 53
                        },
                        new
                        {
                            RoleId = 54,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 469, DateTimeKind.Utc).AddTicks(7253),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 469, DateTimeKind.Utc).AddTicks(7258),
                            UserId = 54
                        },
                        new
                        {
                            RoleId = 55,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 542, DateTimeKind.Utc).AddTicks(4107),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 542, DateTimeKind.Utc).AddTicks(4112),
                            UserId = 55
                        },
                        new
                        {
                            RoleId = 56,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 611, DateTimeKind.Utc).AddTicks(3399),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 611, DateTimeKind.Utc).AddTicks(3405),
                            UserId = 56
                        },
                        new
                        {
                            RoleId = 57,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 681, DateTimeKind.Utc).AddTicks(4682),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 681, DateTimeKind.Utc).AddTicks(4688),
                            UserId = 57
                        },
                        new
                        {
                            RoleId = 58,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 750, DateTimeKind.Utc).AddTicks(6021),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 750, DateTimeKind.Utc).AddTicks(6026),
                            UserId = 58
                        },
                        new
                        {
                            RoleId = 59,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 823, DateTimeKind.Utc).AddTicks(7275),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 823, DateTimeKind.Utc).AddTicks(7280),
                            UserId = 59
                        },
                        new
                        {
                            RoleId = 60,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 896, DateTimeKind.Utc).AddTicks(572),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 896, DateTimeKind.Utc).AddTicks(576),
                            UserId = 60
                        },
                        new
                        {
                            RoleId = 61,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 970, DateTimeKind.Utc).AddTicks(3734),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 970, DateTimeKind.Utc).AddTicks(3738),
                            UserId = 61
                        },
                        new
                        {
                            RoleId = 62,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 42, DateTimeKind.Utc).AddTicks(7061),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 42, DateTimeKind.Utc).AddTicks(7066),
                            UserId = 62
                        },
                        new
                        {
                            RoleId = 63,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 111, DateTimeKind.Utc).AddTicks(8059),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 111, DateTimeKind.Utc).AddTicks(8064),
                            UserId = 63
                        },
                        new
                        {
                            RoleId = 64,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 182, DateTimeKind.Utc).AddTicks(8542),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 182, DateTimeKind.Utc).AddTicks(8549),
                            UserId = 64
                        },
                        new
                        {
                            RoleId = 65,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 258, DateTimeKind.Utc).AddTicks(3621),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 258, DateTimeKind.Utc).AddTicks(3626),
                            UserId = 65
                        },
                        new
                        {
                            RoleId = 66,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 332, DateTimeKind.Utc).AddTicks(9388),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 332, DateTimeKind.Utc).AddTicks(9394),
                            UserId = 66
                        },
                        new
                        {
                            RoleId = 67,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 410, DateTimeKind.Utc).AddTicks(3455),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 410, DateTimeKind.Utc).AddTicks(3463),
                            UserId = 67
                        },
                        new
                        {
                            RoleId = 68,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 483, DateTimeKind.Utc).AddTicks(6227),
                            RoleType = 1,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 483, DateTimeKind.Utc).AddTicks(6231),
                            UserId = 68
                        },
                        new
                        {
                            RoleId = 70,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 553, DateTimeKind.Utc).AddTicks(8610),
                            RoleType = 2,
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 553, DateTimeKind.Utc).AddTicks(8615),
                            UserId = 69
                        });
                });

            modelBuilder.Entity("TeamFive.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 692, DateTimeKind.Utc).AddTicks(7790),
                            Email = "brittany.hyatt@email.com",
                            FirstName = "Brittany",
                            LastName = "Hyatt",
                            Password = "AQAAAAIAAYagAAAAEP6Ew4Jhp2f5hW7GF1Vpgt7yIPO2Ge3VUtVwrJ3Oc2sRpE2kW0xYhoPakLcgZ5+JCw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 692, DateTimeKind.Utc).AddTicks(7792)
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 761, DateTimeKind.Utc).AddTicks(6498),
                            Email = "lavon.kunze@email.com",
                            FirstName = "Lavon",
                            LastName = "Kunze",
                            Password = "AQAAAAIAAYagAAAAEKhwG7ipvO5xjdEcTUdaY2lp5EC32Q6Zf8krJ5FtoZF0YhHOac/bqB4B4I1bkntHUg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 761, DateTimeKind.Utc).AddTicks(6499)
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 831, DateTimeKind.Utc).AddTicks(7911),
                            Email = "mose.walker@email.com",
                            FirstName = "Mose",
                            LastName = "Walker",
                            Password = "AQAAAAIAAYagAAAAEORhgvKGoaeu5pHQAIBMmbASKJDHARx4dr3PdND3KbT+O+VyooS31S2Enf51p1hljQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 831, DateTimeKind.Utc).AddTicks(7912)
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 902, DateTimeKind.Utc).AddTicks(2114),
                            Email = "colton.dietrich@email.com",
                            FirstName = "Colton",
                            LastName = "Dietrich",
                            Password = "AQAAAAIAAYagAAAAEIMGpyNEYKHZj5Chkm4wkmYbSQxdVSlolBhIhqWfYKK/3NQY7F3u6a37XN5gVBBcFA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 902, DateTimeKind.Utc).AddTicks(2120)
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 973, DateTimeKind.Utc).AddTicks(1689),
                            Email = "rex.hagenes@email.com",
                            FirstName = "Rex",
                            LastName = "Hagenes",
                            Password = "AQAAAAIAAYagAAAAEEkSoR4ZslmjVz+qj6kn3iAiuPV5VM1lLdQNVqY4pAfNFpasi20Cg2JOiO+s+qWY3Q==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 973, DateTimeKind.Utc).AddTicks(1692)
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 43, DateTimeKind.Utc).AddTicks(9052),
                            Email = "bruce.schneider@email.com",
                            FirstName = "Bruce",
                            LastName = "Schneider",
                            Password = "AQAAAAIAAYagAAAAEJdOP+9Bi9PpAj9XJSPkCTTuDU3wJwriKpG3rzNYL2jIF1ZWgOMBfoJ3ZZqiRmgEhw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 43, DateTimeKind.Utc).AddTicks(9054)
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 114, DateTimeKind.Utc).AddTicks(6834),
                            Email = "allen.hoppe@email.com",
                            FirstName = "Allen",
                            LastName = "Hoppe",
                            Password = "AQAAAAIAAYagAAAAEI0GjZqHVIIn/amzSCwiM3Zt4xkqCj7Di3igx/WwZNfruA21UstAD2rBsOTdJ1I7+w==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 114, DateTimeKind.Utc).AddTicks(6835)
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 184, DateTimeKind.Utc).AddTicks(6515),
                            Email = "ludwig.yost@email.com",
                            FirstName = "Ludwig",
                            LastName = "Yost",
                            Password = "AQAAAAIAAYagAAAAEDMOpp9b+TI1WxOUjWPt0Ltxcbb/CEw8E1AmahrIA2w32cOUS2I5KDQqIkvxTcKF1g==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 184, DateTimeKind.Utc).AddTicks(6516)
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 254, DateTimeKind.Utc).AddTicks(7522),
                            Email = "hassie.armstrong@email.com",
                            FirstName = "Hassie",
                            LastName = "Armstrong",
                            Password = "AQAAAAIAAYagAAAAEEfMJiLEdy/Fw0KChGl2IDTWY7OzdJv8GSAEGxvX7UxLLQWhbZXPXGoaJU6Z9aKSbw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 254, DateTimeKind.Utc).AddTicks(7523)
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 325, DateTimeKind.Utc).AddTicks(1916),
                            Email = "alvis.lakin@email.com",
                            FirstName = "Alvis",
                            LastName = "Lakin",
                            Password = "AQAAAAIAAYagAAAAEDohmh5v01Jhn7hRmfuk/8Ug/twkQe5GfVAtlpz0VnrH+tDYjeaAZcX2I+OA1MsX2g==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 325, DateTimeKind.Utc).AddTicks(1917)
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 396, DateTimeKind.Utc).AddTicks(5764),
                            Email = "addie.effertz@email.com",
                            FirstName = "Addie",
                            LastName = "Effertz",
                            Password = "AQAAAAIAAYagAAAAEBZKFUN2bgm0UWeizStvRAmhc8MD+ySu90+9csTM6jnrvi1e7hbdmo2+wQw9RlrnPQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 396, DateTimeKind.Utc).AddTicks(5766)
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 466, DateTimeKind.Utc).AddTicks(8670),
                            Email = "vincenza.rosenbaum@email.com",
                            FirstName = "Vincenza",
                            LastName = "Rosenbaum",
                            Password = "AQAAAAIAAYagAAAAELsa7osBWC/kOUcn/yWhC0hV8Li4VMTnvjimzkY2tO4k17Kv5lK7F5tCPuHmkH/qbA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 466, DateTimeKind.Utc).AddTicks(8672)
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 536, DateTimeKind.Utc).AddTicks(1330),
                            Email = "zackary.doyle@email.com",
                            FirstName = "Zackary",
                            LastName = "Doyle",
                            Password = "AQAAAAIAAYagAAAAEBdnuRwhvtETqe+wUBE2qs7ZguTAl8a5gQXuG6ytLhS78ITu4zjuntKEju+X94XoxQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 536, DateTimeKind.Utc).AddTicks(1331)
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 605, DateTimeKind.Utc).AddTicks(9506),
                            Email = "modesta.schroeder@email.com",
                            FirstName = "Modesta",
                            LastName = "Schroeder",
                            Password = "AQAAAAIAAYagAAAAEPq6q0jfFyptUtVNu6wk3kGJxl1gXnFhmBYQK/01BMCCLw4XYHESxy1aAWud/xHW5g==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 605, DateTimeKind.Utc).AddTicks(9507)
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 675, DateTimeKind.Utc).AddTicks(5529),
                            Email = "amira.jacobi@email.com",
                            FirstName = "Amira",
                            LastName = "Jacobi",
                            Password = "AQAAAAIAAYagAAAAEKtDBf2O53fMQajBmytzwn4cXoBJuIGVKPE2bAhy+P+3TBYbNCTtpEYVI+KH8mbUgw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 675, DateTimeKind.Utc).AddTicks(5530)
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 745, DateTimeKind.Utc).AddTicks(7772),
                            Email = "henry.jenkins@email.com",
                            FirstName = "Henry",
                            LastName = "Jenkins",
                            Password = "AQAAAAIAAYagAAAAEDeEvszz1lgikeXzyybs8WcqTWbBQ4hCtXdiAE3l3LtNovp0YXZtG6pUlKgeal2mQw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 745, DateTimeKind.Utc).AddTicks(7772)
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 816, DateTimeKind.Utc).AddTicks(2051),
                            Email = "trenton.metz@email.com",
                            FirstName = "Trenton",
                            LastName = "Metz",
                            Password = "AQAAAAIAAYagAAAAEMOw4kfLsIhnQq1SLz8enRfvg2rqXyEYgFsKFZOvnTjkUVDThcU4jHod9LtuKaJTcw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 816, DateTimeKind.Utc).AddTicks(2052)
                        },
                        new
                        {
                            UserId = 18,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 888, DateTimeKind.Utc).AddTicks(6507),
                            Email = "jed.gleichner@email.com",
                            FirstName = "Jed",
                            LastName = "Gleichner",
                            Password = "AQAAAAIAAYagAAAAEDjiZwJci/ilHjAzXc8F9DNle928wtaGTCcF2N3rzeTVKJd6+tMpU4IRZE4dLFTTrQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 888, DateTimeKind.Utc).AddTicks(6511)
                        },
                        new
                        {
                            UserId = 19,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 958, DateTimeKind.Utc).AddTicks(9643),
                            Email = "eli.thompson@email.com",
                            FirstName = "Eli",
                            LastName = "Thompson",
                            Password = "AQAAAAIAAYagAAAAEH0+CiRce0AxcXB8/ZLqjmNwMKc6flFEAdnsZG/RDJsmIyIw/Nvxy0EZYyGO2ZPWwA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 958, DateTimeKind.Utc).AddTicks(9645)
                        },
                        new
                        {
                            UserId = 20,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 29, DateTimeKind.Utc).AddTicks(5622),
                            Email = "luz.runte@email.com",
                            FirstName = "Luz",
                            LastName = "Runte",
                            Password = "AQAAAAIAAYagAAAAEN7Y1zJoFUQoDu9W91x3x5z1qrZvfSwytZNO9u665pBV7wchP185soUw7iMThhkR9A==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 29, DateTimeKind.Utc).AddTicks(5623)
                        },
                        new
                        {
                            UserId = 21,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 98, DateTimeKind.Utc).AddTicks(1812),
                            Email = "margaretta.stracke@email.com",
                            FirstName = "Margaretta",
                            LastName = "Stracke",
                            Password = "AQAAAAIAAYagAAAAEAhFTHJcQEPwIyarPa7z1XI6gCDbgzJljE5Uuf2E36YACBFYZY3GL76ZjyXI53yPeQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 98, DateTimeKind.Utc).AddTicks(1814)
                        },
                        new
                        {
                            UserId = 22,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 168, DateTimeKind.Utc).AddTicks(6102),
                            Email = "marilou.reilly@email.com",
                            FirstName = "Marilou",
                            LastName = "Reilly",
                            Password = "AQAAAAIAAYagAAAAEGqFNkWkJYYAvztoNTwpMi2d9Kc3aAtvPysBsFkd7+JJIkYg19VkLOlgserd4uQyMw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 168, DateTimeKind.Utc).AddTicks(6102)
                        },
                        new
                        {
                            UserId = 23,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 237, DateTimeKind.Utc).AddTicks(9013),
                            Email = "sofia.crona@email.com",
                            FirstName = "Sofia",
                            LastName = "Crona",
                            Password = "AQAAAAIAAYagAAAAEDkQQZadXuqueq0zWlQk+bPIDxVUSsD5v6yS3kakqDayiM5L3l3IIT5qY9ROjaBLhw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 237, DateTimeKind.Utc).AddTicks(9015)
                        },
                        new
                        {
                            UserId = 24,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 307, DateTimeKind.Utc).AddTicks(8334),
                            Email = "connie.jacobi@email.com",
                            FirstName = "Connie",
                            LastName = "Jacobi",
                            Password = "AQAAAAIAAYagAAAAED9Cbl/ZsuzfDrt55KKKM5RNNwlMJZNQGcBz70eMKQxRdUNZ1BUkqrhlCaCx0uvXpA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 307, DateTimeKind.Utc).AddTicks(8335)
                        },
                        new
                        {
                            UserId = 25,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 377, DateTimeKind.Utc).AddTicks(3855),
                            Email = "alexane.dach@email.com",
                            FirstName = "Alexane",
                            LastName = "Dach",
                            Password = "AQAAAAIAAYagAAAAEEhyzn/taQOGZj1gO7UigMnfVl5/75DbDjAOIvffeMukGSN2sjYig9mE+3w4GHO+8A==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 377, DateTimeKind.Utc).AddTicks(3856)
                        },
                        new
                        {
                            UserId = 26,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 446, DateTimeKind.Utc).AddTicks(8975),
                            Email = "hope.ferry@email.com",
                            FirstName = "Hope",
                            LastName = "Ferry",
                            Password = "AQAAAAIAAYagAAAAEC1us6dWKopCsUD+UIfsA3rGdQi8j1/O6D5LIS5/c9PoVnrDc294JGWsPfMX9/BTlw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 446, DateTimeKind.Utc).AddTicks(8976)
                        },
                        new
                        {
                            UserId = 27,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 515, DateTimeKind.Utc).AddTicks(6838),
                            Email = "demond.orn@email.com",
                            FirstName = "Demond",
                            LastName = "Orn",
                            Password = "AQAAAAIAAYagAAAAEApfPfi1z1iyJCclAyzqZmzA/suy4szn4s5VzlKwU7zm1jPxtf/G7ym1bvfd6de5og==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 515, DateTimeKind.Utc).AddTicks(6841)
                        },
                        new
                        {
                            UserId = 28,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 585, DateTimeKind.Utc).AddTicks(8254),
                            Email = "jamaal.metz@email.com",
                            FirstName = "Jamaal",
                            LastName = "Metz",
                            Password = "AQAAAAIAAYagAAAAEA/KBhVR0cVDMEkXBavaar9FjCTLKNB1f/f6tpTT0fNpCcietuKcbFkltz9LIgg3Wg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 585, DateTimeKind.Utc).AddTicks(8255)
                        },
                        new
                        {
                            UserId = 29,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 655, DateTimeKind.Utc).AddTicks(8781),
                            Email = "nels.dickinson@email.com",
                            FirstName = "Nels",
                            LastName = "Dickinson",
                            Password = "AQAAAAIAAYagAAAAELmWOLhQ3LBOVZKewk8XRwDZbejBcoQFgo7aEpB5f15s0FQ4NPcF9SlEwz+RtvaoGA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 655, DateTimeKind.Utc).AddTicks(8782)
                        },
                        new
                        {
                            UserId = 30,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 725, DateTimeKind.Utc).AddTicks(6645),
                            Email = "terry.macgyver@email.com",
                            FirstName = "Terry",
                            LastName = "MacGyver",
                            Password = "AQAAAAIAAYagAAAAEK3b576qP801iHkMcbtReZtj00IewN3YtBC4Jm1HJljXOmXmPcjK0Z/CxluDryjljw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 725, DateTimeKind.Utc).AddTicks(6646)
                        },
                        new
                        {
                            UserId = 31,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 794, DateTimeKind.Utc).AddTicks(5799),
                            Email = "reuben.price@email.com",
                            FirstName = "Reuben",
                            LastName = "Price",
                            Password = "AQAAAAIAAYagAAAAEHEmsEc91Qda6+5eXAgTljW/YKh7J/FYT9qpgOy2k8UAnMw9WB7qOZU8ezpHRtdhiA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 794, DateTimeKind.Utc).AddTicks(5801)
                        },
                        new
                        {
                            UserId = 32,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 864, DateTimeKind.Utc).AddTicks(5969),
                            Email = "jolie.strosin@email.com",
                            FirstName = "Jolie",
                            LastName = "Strosin",
                            Password = "AQAAAAIAAYagAAAAEPCNRBTBK7jAQ3nqFnM7YAk59iyW9PXMDhHzwMmFoiF0U+96bnmGNoqdJPwtUTj1Ew==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 864, DateTimeKind.Utc).AddTicks(5969)
                        },
                        new
                        {
                            UserId = 33,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 934, DateTimeKind.Utc).AddTicks(6879),
                            Email = "keshaun.hackett@email.com",
                            FirstName = "Keshaun",
                            LastName = "Hackett",
                            Password = "AQAAAAIAAYagAAAAEJoBbncN8vCEJqRrWxHbSfCTovi2Kc7eOXhReB38LuJ/WgcQoJ0bYo2HqI8stf7hgg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 5, 934, DateTimeKind.Utc).AddTicks(6880)
                        },
                        new
                        {
                            UserId = 34,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 5, DateTimeKind.Utc).AddTicks(179),
                            Email = "gus.romaguera@email.com",
                            FirstName = "Gus",
                            LastName = "Romaguera",
                            Password = "AQAAAAIAAYagAAAAEF93Cg9nl3Pp0zPdVhbh/sdODjErlehFrjGAOgDdqocShm2bBA04vLSnw7uJBDyriQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 5, DateTimeKind.Utc).AddTicks(180)
                        },
                        new
                        {
                            UserId = 35,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 75, DateTimeKind.Utc).AddTicks(464),
                            Email = "rollin.boehm@email.com",
                            FirstName = "Rollin",
                            LastName = "Boehm",
                            Password = "AQAAAAIAAYagAAAAEL2V51eryf5wLMcDi4Fc30UjTzqIn6H9JGuHqovbTUnmYlp6ngLSHbJxCUUOj0SeDg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 75, DateTimeKind.Utc).AddTicks(465)
                        },
                        new
                        {
                            UserId = 36,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 145, DateTimeKind.Utc).AddTicks(2835),
                            Email = "arlie.franecki@email.com",
                            FirstName = "Arlie",
                            LastName = "Franecki",
                            Password = "AQAAAAIAAYagAAAAENUd3W5HDofkV7cmYgODVrJV9yRE+gZ8mbCALuY+2hkIGry719OUcsv/suBJG4T3+w==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 145, DateTimeKind.Utc).AddTicks(2841)
                        },
                        new
                        {
                            UserId = 37,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 214, DateTimeKind.Utc).AddTicks(6522),
                            Email = "leif.wisozk@email.com",
                            FirstName = "Leif",
                            LastName = "Wisozk",
                            Password = "AQAAAAIAAYagAAAAEH6xDRTT4Gpj/Gp0yfVZ1pX4Q8ijmyN+GkwKPZj7LzxyB6SNKF5zQICaK0j4LJbv7w==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 214, DateTimeKind.Utc).AddTicks(6525)
                        },
                        new
                        {
                            UserId = 38,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 284, DateTimeKind.Utc).AddTicks(2650),
                            Email = "katelyn.jaskolski@email.com",
                            FirstName = "Katelyn",
                            LastName = "Jaskolski",
                            Password = "AQAAAAIAAYagAAAAEG3SdVRYHvcVT6wLu37il0x650BQ0N6usGdWRowSlHTWOeV02kgPG5cYUphp2V2tIA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 284, DateTimeKind.Utc).AddTicks(2652)
                        },
                        new
                        {
                            UserId = 39,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 354, DateTimeKind.Utc).AddTicks(4011),
                            Email = "howell.ritchie@email.com",
                            FirstName = "Howell",
                            LastName = "Ritchie",
                            Password = "AQAAAAIAAYagAAAAEHx5Cs6qqtFwGd+SZ8pWRcjHHGqZzjw6AYR/g9wv5Ja3V5UFuBw63wL8zmLiDdX3/A==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 354, DateTimeKind.Utc).AddTicks(4012)
                        },
                        new
                        {
                            UserId = 40,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 423, DateTimeKind.Utc).AddTicks(7152),
                            Email = "alexandrea.lind@email.com",
                            FirstName = "Alexandrea",
                            LastName = "Lind",
                            Password = "AQAAAAIAAYagAAAAEG5dwD6NHdo6xg/JK/pKcsFhV/7CgTtcCFpLBGRjor5O3Z5vI8z/Ewyb99x749Sb4A==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 423, DateTimeKind.Utc).AddTicks(7155)
                        },
                        new
                        {
                            UserId = 41,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 493, DateTimeKind.Utc).AddTicks(1175),
                            Email = "kali.o'hara@email.com",
                            FirstName = "Kali",
                            LastName = "O'Hara",
                            Password = "AQAAAAIAAYagAAAAEEA/yMwlBT3tmS99PdAWJ+oMYbJYlS5AF5oG9/IZq3eVKAtSMeCUrbsPo3o1Pz28OQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 493, DateTimeKind.Utc).AddTicks(1177)
                        },
                        new
                        {
                            UserId = 42,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 563, DateTimeKind.Utc).AddTicks(2125),
                            Email = "samanta.streich@email.com",
                            FirstName = "Samanta",
                            LastName = "Streich",
                            Password = "AQAAAAIAAYagAAAAECcchjJOsW1iSB7cVqfTQxfiKp2k1JFLB+4VT9nsqj6ynuHWkPD+kYmnWSrlcDqelA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 563, DateTimeKind.Utc).AddTicks(2129)
                        },
                        new
                        {
                            UserId = 43,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 632, DateTimeKind.Utc).AddTicks(7106),
                            Email = "dolly.prosacco@email.com",
                            FirstName = "Dolly",
                            LastName = "Prosacco",
                            Password = "AQAAAAIAAYagAAAAECrng+71NqiRgN//8c9SVYMkVjy0lFbCDU3jZWmORAqiTFy+7NVWszbelVHyfumdcQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 632, DateTimeKind.Utc).AddTicks(7109)
                        },
                        new
                        {
                            UserId = 44,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 702, DateTimeKind.Utc).AddTicks(6397),
                            Email = "celestino.bahringer@email.com",
                            FirstName = "Celestino",
                            LastName = "Bahringer",
                            Password = "AQAAAAIAAYagAAAAEA0dcEiyW8KKrSERfsjICTWUEw5k+IuLien9WUuFJCLxXi1nURNkl/g9+cJ6gC1eMQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 702, DateTimeKind.Utc).AddTicks(6399)
                        },
                        new
                        {
                            UserId = 45,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 772, DateTimeKind.Utc).AddTicks(520),
                            Email = "jedidiah.glover@email.com",
                            FirstName = "Jedidiah",
                            LastName = "Glover",
                            Password = "AQAAAAIAAYagAAAAEIU8MTw2cCGUnvpQV6SV+bM0H8QdmO39kpTbNMhEyc1gzHjtN6k6Ugr6+KgAoLqhMw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 772, DateTimeKind.Utc).AddTicks(521)
                        },
                        new
                        {
                            UserId = 46,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 842, DateTimeKind.Utc).AddTicks(1118),
                            Email = "schuyler.jaskolski@email.com",
                            FirstName = "Schuyler",
                            LastName = "Jaskolski",
                            Password = "AQAAAAIAAYagAAAAEH6MgqtlH8iOCUT0LGOnb+9SXvf/kvzxebWWmtjKl59JUCNDin0DnebDPI8Dw7qUQA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 842, DateTimeKind.Utc).AddTicks(1119)
                        },
                        new
                        {
                            UserId = 47,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 911, DateTimeKind.Utc).AddTicks(9754),
                            Email = "faye.hilll@email.com",
                            FirstName = "Faye",
                            LastName = "Hilll",
                            Password = "AQAAAAIAAYagAAAAEAyGxlEOxVXNPKMImobUC3UQAR1cwOaQaX3wgSfYs9U4zzDBXVKYOCwQS3J0sKmQng==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 911, DateTimeKind.Utc).AddTicks(9755)
                        },
                        new
                        {
                            UserId = 48,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 982, DateTimeKind.Utc).AddTicks(3479),
                            Email = "johathan.hahn@email.com",
                            FirstName = "Johathan",
                            LastName = "Hahn",
                            Password = "AQAAAAIAAYagAAAAEMm8tBjFrAgJpfavWwJB3duzfDzWFxclIEXWMkHzZ3yk9Y70sVQaKXx84wkT77hjQA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 6, 982, DateTimeKind.Utc).AddTicks(3481)
                        },
                        new
                        {
                            UserId = 49,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 50, DateTimeKind.Utc).AddTicks(8705),
                            Email = "eldred.mueller@email.com",
                            FirstName = "Eldred",
                            LastName = "Mueller",
                            Password = "AQAAAAIAAYagAAAAEKNPmszAwH7w0Sbpk19ZAWev0WwpPFpNC6k/p256xkvHDjkY/cAN69EABSK9h6WUjw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 50, DateTimeKind.Utc).AddTicks(8706)
                        },
                        new
                        {
                            UserId = 50,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 120, DateTimeKind.Utc).AddTicks(605),
                            Email = "norma.conroy@email.com",
                            FirstName = "Norma",
                            LastName = "Conroy",
                            Password = "AQAAAAIAAYagAAAAEPatxUW0p/mJlttJrIYpJkR+3fOacdusUfYLv+edotl+5fISr8nEpAcirVAel+akCQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 120, DateTimeKind.Utc).AddTicks(606)
                        },
                        new
                        {
                            UserId = 51,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 190, DateTimeKind.Utc).AddTicks(3308),
                            Email = "joany.lindgren@email.com",
                            FirstName = "Joany",
                            LastName = "Lindgren",
                            Password = "AQAAAAIAAYagAAAAEOs+3zreXraYI0bTwdULahQ3QkUSEQeadZ9HvyxG0ONDovNlLNZmX8gVQSdaqNv/Zw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 190, DateTimeKind.Utc).AddTicks(3310)
                        },
                        new
                        {
                            UserId = 52,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 259, DateTimeKind.Utc).AddTicks(8819),
                            Email = "rosario.howe@email.com",
                            FirstName = "Rosario",
                            LastName = "Howe",
                            Password = "AQAAAAIAAYagAAAAEIAJoOJwVw6IIwI3y1EU0OwiizrWjxf2VZ8mVHRAfgdCctjaAjFdFA8IMnFk6X4FhA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 259, DateTimeKind.Utc).AddTicks(8821)
                        },
                        new
                        {
                            UserId = 53,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 330, DateTimeKind.Utc).AddTicks(3227),
                            Email = "jacey.emmerich@email.com",
                            FirstName = "Jacey",
                            LastName = "Emmerich",
                            Password = "AQAAAAIAAYagAAAAEDtG3P/tYTPQTeVYGDLONfwRRcp33SguIDTabQjKqoJXCytqi9dVt9mo2fwrYGGwvw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 330, DateTimeKind.Utc).AddTicks(3229)
                        },
                        new
                        {
                            UserId = 54,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 399, DateTimeKind.Utc).AddTicks(5883),
                            Email = "damian.bednar@email.com",
                            FirstName = "Damian",
                            LastName = "Bednar",
                            Password = "AQAAAAIAAYagAAAAEIGv6hM0LBBpnFkp51vujTkMKWMljabKC7o89Z8qMhJEyT78d9yYrshAUD0wveCUFg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 399, DateTimeKind.Utc).AddTicks(5884)
                        },
                        new
                        {
                            UserId = 55,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 471, DateTimeKind.Utc).AddTicks(1499),
                            Email = "howell.hansen@email.com",
                            FirstName = "Howell",
                            LastName = "Hansen",
                            Password = "AQAAAAIAAYagAAAAEO/Aid89OU29zq+Xo6XGkxfk99SEt88sM+nzFmrBY2Suis3Eyf5kJUtpGEuJGAzDTA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 471, DateTimeKind.Utc).AddTicks(1501)
                        },
                        new
                        {
                            UserId = 56,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 543, DateTimeKind.Utc).AddTicks(7794),
                            Email = "albert.williamson@email.com",
                            FirstName = "Albert",
                            LastName = "Williamson",
                            Password = "AQAAAAIAAYagAAAAEA9IntEUTsO2Qvxk84n0tvm7GLjMqZ2JrH4hNO/ogdO/KnRvd0BGGJHWORQ/0pS22g==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 543, DateTimeKind.Utc).AddTicks(7796)
                        },
                        new
                        {
                            UserId = 57,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 612, DateTimeKind.Utc).AddTicks(7146),
                            Email = "kaitlin.brown@email.com",
                            FirstName = "Kaitlin",
                            LastName = "Brown",
                            Password = "AQAAAAIAAYagAAAAEESOv6Wlq/4JnMFspUZ79SztUmwuVbLC1a9er+FaiWvVYL39Iqhf643BVhvcQ5p6iw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 612, DateTimeKind.Utc).AddTicks(7147)
                        },
                        new
                        {
                            UserId = 58,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 682, DateTimeKind.Utc).AddTicks(8063),
                            Email = "ansley.stracke@email.com",
                            FirstName = "Ansley",
                            LastName = "Stracke",
                            Password = "AQAAAAIAAYagAAAAEHH6fXu477MFYAjrY3uNSuPoe3YLRLFeSTjUbSasKdmBiitVTMhZjTHgJRM2UPHwRg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 682, DateTimeKind.Utc).AddTicks(8064)
                        },
                        new
                        {
                            UserId = 59,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 751, DateTimeKind.Utc).AddTicks(9058),
                            Email = "fritz.olson@email.com",
                            FirstName = "Fritz",
                            LastName = "Olson",
                            Password = "AQAAAAIAAYagAAAAEOQ9q4ITwpxw8KRljneywbkifutSN9VOJafdm7xaltF7VqK8XpU7ao6GMfMIkblgtw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 751, DateTimeKind.Utc).AddTicks(9060)
                        },
                        new
                        {
                            UserId = 60,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 825, DateTimeKind.Utc).AddTicks(1735),
                            Email = "graciela.zulauf@email.com",
                            FirstName = "Graciela",
                            LastName = "Zulauf",
                            Password = "AQAAAAIAAYagAAAAEIlQlLSzX29/oXXuIca+S7FzGvCMbJ8kHTJ3PZtcOf1kZF2Mv646u8vbbyGB+FneaA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 825, DateTimeKind.Utc).AddTicks(1737)
                        },
                        new
                        {
                            UserId = 61,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 897, DateTimeKind.Utc).AddTicks(4044),
                            Email = "shaylee.ernser@email.com",
                            FirstName = "Shaylee",
                            LastName = "Ernser",
                            Password = "AQAAAAIAAYagAAAAEDIdYH5waVO56zP7ASWBZ4hfmBgmIcSRqgZQZxY+FfG8AJFRyRbpVbMTkp4nW6UtHg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 897, DateTimeKind.Utc).AddTicks(4045)
                        },
                        new
                        {
                            UserId = 62,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 972, DateTimeKind.Utc).AddTicks(6792),
                            Email = "uriel.kuhn@email.com",
                            FirstName = "Uriel",
                            LastName = "Kuhn",
                            Password = "AQAAAAIAAYagAAAAEDDhc/3j6oE4ulS9Xl+CrCXyaAMn6EPNMwIuRTrjJUthRjkLpdjSWNShxgpU6svM6w==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 7, 972, DateTimeKind.Utc).AddTicks(6795)
                        },
                        new
                        {
                            UserId = 63,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 44, DateTimeKind.Utc).AddTicks(229),
                            Email = "erik.weimann@email.com",
                            FirstName = "Erik",
                            LastName = "Weimann",
                            Password = "AQAAAAIAAYagAAAAEKUQw7cmyFy+YFGTwHJNFyIaIwPxcDxm+80WdW7KOSDZRIC1c+k8MaaP407oFTdOZw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 44, DateTimeKind.Utc).AddTicks(229)
                        },
                        new
                        {
                            UserId = 64,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 113, DateTimeKind.Utc).AddTicks(2686),
                            Email = "anahi.champlin@email.com",
                            FirstName = "Anahi",
                            LastName = "Champlin",
                            Password = "AQAAAAIAAYagAAAAEG00w78tPKuMXWjZWvs1Q7GXyqjqa7YvTC5Al5l867KPXb44hOZSwvPZp9oX/wjskQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 113, DateTimeKind.Utc).AddTicks(2687)
                        },
                        new
                        {
                            UserId = 65,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 184, DateTimeKind.Utc).AddTicks(3421),
                            Email = "allie.flatley@email.com",
                            FirstName = "Allie",
                            LastName = "Flatley",
                            Password = "AQAAAAIAAYagAAAAEKqNBkcBEnRTh5ldSOoe/x3isEcOsXvwOhGFZSywoN/1txco5XHManDCTzhHKb5BTA==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 184, DateTimeKind.Utc).AddTicks(3423)
                        },
                        new
                        {
                            UserId = 66,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 259, DateTimeKind.Utc).AddTicks(7146),
                            Email = "candelario.hand@email.com",
                            FirstName = "Candelario",
                            LastName = "Hand",
                            Password = "AQAAAAIAAYagAAAAEN4Cqv8s3cwYdh/P2ZPE17huQtV4gvKJnFxyAhGVf68+27qSMuki75ijnJuhAuo3qQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 259, DateTimeKind.Utc).AddTicks(7148)
                        },
                        new
                        {
                            UserId = 67,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 334, DateTimeKind.Utc).AddTicks(6208),
                            Email = "kevin.russel@email.com",
                            FirstName = "Kevin",
                            LastName = "Russel",
                            Password = "AQAAAAIAAYagAAAAEJI6jdoXJdJmWGd3oYLsitCBGA7DRoyloOTUQcCEJ/8gFwrkI5GrXCR5/6D09/ernQ==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 334, DateTimeKind.Utc).AddTicks(6211)
                        },
                        new
                        {
                            UserId = 68,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 411, DateTimeKind.Utc).AddTicks(8287),
                            Email = "dayton.bechtelar@email.com",
                            FirstName = "Dayton",
                            LastName = "Bechtelar",
                            Password = "AQAAAAIAAYagAAAAEPed+yyNxuLDdzhqCi+JAx4wx+PvCKzTCTOJ596LWMGOl+G5DCC3jgTKdzbs40TMBg==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 411, DateTimeKind.Utc).AddTicks(8292)
                        },
                        new
                        {
                            UserId = 69,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 483, DateTimeKind.Utc).AddTicks(6377),
                            Email = "superuser@mail.com",
                            FirstName = "super",
                            LastName = "user",
                            Password = "AQAAAAIAAYagAAAAEPA1AwAzs6qY+jZMtpcNhx/Hd8IAAexkAoqGSWjxFjEXfxbfgoKKFjI2BBB6yNQSBw==",
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 8, 483, DateTimeKind.Utc).AddTicks(6378)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.UserInstrument", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("UserInstruments");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            InstrumentId = 1,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 760, DateTimeKind.Utc).AddTicks(3048),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 760, DateTimeKind.Utc).AddTicks(3049)
                        },
                        new
                        {
                            UserId = 2,
                            InstrumentId = 2,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 830, DateTimeKind.Utc).AddTicks(4409),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 830, DateTimeKind.Utc).AddTicks(4409)
                        },
                        new
                        {
                            UserId = 3,
                            InstrumentId = 3,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 900, DateTimeKind.Utc).AddTicks(7911),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 900, DateTimeKind.Utc).AddTicks(7911)
                        },
                        new
                        {
                            UserId = 4,
                            InstrumentId = 4,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 971, DateTimeKind.Utc).AddTicks(5469),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 3, 971, DateTimeKind.Utc).AddTicks(5469)
                        },
                        new
                        {
                            UserId = 5,
                            InstrumentId = 5,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 42, DateTimeKind.Utc).AddTicks(5156),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 42, DateTimeKind.Utc).AddTicks(5156)
                        },
                        new
                        {
                            UserId = 6,
                            InstrumentId = 6,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 113, DateTimeKind.Utc).AddTicks(3838),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 113, DateTimeKind.Utc).AddTicks(3838)
                        },
                        new
                        {
                            UserId = 7,
                            InstrumentId = 7,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 183, DateTimeKind.Utc).AddTicks(2456),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 183, DateTimeKind.Utc).AddTicks(2456)
                        },
                        new
                        {
                            UserId = 8,
                            InstrumentId = 8,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 253, DateTimeKind.Utc).AddTicks(3703),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 253, DateTimeKind.Utc).AddTicks(3703)
                        },
                        new
                        {
                            UserId = 9,
                            InstrumentId = 9,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 323, DateTimeKind.Utc).AddTicks(7664),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 323, DateTimeKind.Utc).AddTicks(7665)
                        },
                        new
                        {
                            UserId = 10,
                            InstrumentId = 11,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 394, DateTimeKind.Utc).AddTicks(7573),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 394, DateTimeKind.Utc).AddTicks(7573)
                        },
                        new
                        {
                            UserId = 11,
                            InstrumentId = 12,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 465, DateTimeKind.Utc).AddTicks(4710),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 465, DateTimeKind.Utc).AddTicks(4711)
                        },
                        new
                        {
                            UserId = 12,
                            InstrumentId = 13,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 534, DateTimeKind.Utc).AddTicks(7751),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 534, DateTimeKind.Utc).AddTicks(7751)
                        },
                        new
                        {
                            UserId = 13,
                            InstrumentId = 14,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 604, DateTimeKind.Utc).AddTicks(5597),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 604, DateTimeKind.Utc).AddTicks(5598)
                        },
                        new
                        {
                            UserId = 14,
                            InstrumentId = 15,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 674, DateTimeKind.Utc).AddTicks(2167),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 674, DateTimeKind.Utc).AddTicks(2167)
                        },
                        new
                        {
                            UserId = 15,
                            InstrumentId = 17,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 744, DateTimeKind.Utc).AddTicks(4117),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 744, DateTimeKind.Utc).AddTicks(4117)
                        },
                        new
                        {
                            UserId = 16,
                            InstrumentId = 18,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 814, DateTimeKind.Utc).AddTicks(8653),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 814, DateTimeKind.Utc).AddTicks(8653)
                        },
                        new
                        {
                            UserId = 17,
                            InstrumentId = 19,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 887, DateTimeKind.Utc).AddTicks(2164),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 887, DateTimeKind.Utc).AddTicks(2164)
                        },
                        new
                        {
                            UserId = 18,
                            InstrumentId = 20,
                            CreatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 956, DateTimeKind.Utc).AddTicks(9759),
                            UpdatedAt = new DateTime(2023, 10, 28, 16, 2, 4, 956, DateTimeKind.Utc).AddTicks(9759)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.Lesson", b =>
                {
                    b.HasOne("TeamFive.Models.Instrument", "Instrument")
                        .WithMany("Lessons")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "Student")
                        .WithMany("AttendedLessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "Teacher")
                        .WithMany("TaughtLessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeamFive.Models.RefreshToken", b =>
                {
                    b.HasOne("TeamFive.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamFive.Models.Role", b =>
                {
                    b.HasOne("TeamFive.Models.User", "User")
                        .WithOne("Role")
                        .HasForeignKey("TeamFive.Models.Role", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamFive.Models.UserInstrument", b =>
                {
                    b.HasOne("TeamFive.Models.Instrument", "Instrument")
                        .WithMany("UserInstruments")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "User")
                        .WithMany("UserInstruments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamFive.Models.Instrument", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserInstruments");
                });

            modelBuilder.Entity("TeamFive.Models.User", b =>
                {
                    b.Navigation("AttendedLessons");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Role");

                    b.Navigation("TaughtLessons");

                    b.Navigation("UserInstruments");
                });
#pragma warning restore 612, 618
        }
    }
}
