// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TeamFive.DataStorage;

#nullable disable

namespace TeamFive.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20231011154836_DBRestructure")]
    partial class DBRestructure
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TeamFive.Models.Instrument", b =>
                {
                    b.Property<int>("InstrumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("InstrumentId");

                    b.ToTable("Instruments");

                    b.HasData(
                        new
                        {
                            InstrumentId = 1,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8080),
                            Family = "Keyboard",
                            Name = "Piano",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8080)
                        },
                        new
                        {
                            InstrumentId = 2,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8250),
                            Family = "String",
                            Name = "Guitar",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8250)
                        },
                        new
                        {
                            InstrumentId = 3,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8270),
                            Family = "Woodwind",
                            Name = "Flute",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8270)
                        },
                        new
                        {
                            InstrumentId = 4,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8280),
                            Family = "Percussion",
                            Name = "Drums",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8280)
                        },
                        new
                        {
                            InstrumentId = 5,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8320),
                            Family = "String",
                            Name = "Violin",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8320)
                        },
                        new
                        {
                            InstrumentId = 6,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8330),
                            Family = "Brass",
                            Name = "Trumpet",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8330)
                        },
                        new
                        {
                            InstrumentId = 7,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8350),
                            Family = "Woodwind",
                            Name = "Saxophone",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8350)
                        },
                        new
                        {
                            InstrumentId = 8,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8360),
                            Family = "String",
                            Name = "Bass Guitar",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8360)
                        },
                        new
                        {
                            InstrumentId = 9,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8380),
                            Family = "Woodwind",
                            Name = "Clarinet",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8380)
                        },
                        new
                        {
                            InstrumentId = 11,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8390),
                            Family = "Brass",
                            Name = "Trombone",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8390)
                        },
                        new
                        {
                            InstrumentId = 12,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8420),
                            Family = "String",
                            Name = "Harp",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8420)
                        },
                        new
                        {
                            InstrumentId = 13,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8430),
                            Family = "Percussion",
                            Name = "Vibrophone",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8430)
                        },
                        new
                        {
                            InstrumentId = 14,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8450),
                            Family = "Woodwind",
                            Name = "Oboe",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            InstrumentId = 15,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8460),
                            Family = "Woodwind",
                            Name = "Bassoon",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8460)
                        },
                        new
                        {
                            InstrumentId = 17,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8470),
                            Family = "String",
                            Name = "Classical Guitar",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8470)
                        },
                        new
                        {
                            InstrumentId = 18,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8500),
                            Family = "Brass",
                            Name = "French Horn",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8500)
                        },
                        new
                        {
                            InstrumentId = 19,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8510),
                            Family = "Keyboard",
                            Name = "Accordion",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8510)
                        },
                        new
                        {
                            InstrumentId = 20,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8520),
                            Family = "String",
                            Name = "Cello",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 955, DateTimeKind.Utc).AddTicks(8520)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.Lesson", b =>
                {
                    b.Property<int>("LessonId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("BookingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<int>("StudentId")
                        .HasColumnType("int");

                    b.Property<int>("TeacherId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("LessonId");

                    b.HasIndex("InstrumentId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TeacherId");

                    b.ToTable("Lessons");
                });

            modelBuilder.Entity("TeamFive.Models.RefreshToken", b =>
                {
                    b.Property<int>("RefreshTokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("Expiry")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("RefreshTokenId");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("TeamFive.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Bio")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RoleType")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 20, DateTimeKind.Utc).AddTicks(6610),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 20, DateTimeKind.Utc).AddTicks(6610)
                        },
                        new
                        {
                            RoleId = 2,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 85, DateTimeKind.Utc).AddTicks(2700),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 85, DateTimeKind.Utc).AddTicks(2700)
                        },
                        new
                        {
                            RoleId = 3,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 151, DateTimeKind.Utc).AddTicks(7300),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 151, DateTimeKind.Utc).AddTicks(7300)
                        },
                        new
                        {
                            RoleId = 4,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 218, DateTimeKind.Utc).AddTicks(220),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 218, DateTimeKind.Utc).AddTicks(220)
                        },
                        new
                        {
                            RoleId = 5,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 282, DateTimeKind.Utc).AddTicks(2030),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 282, DateTimeKind.Utc).AddTicks(2030)
                        },
                        new
                        {
                            RoleId = 6,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 347, DateTimeKind.Utc).AddTicks(1910),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 347, DateTimeKind.Utc).AddTicks(1910)
                        },
                        new
                        {
                            RoleId = 7,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 412, DateTimeKind.Utc).AddTicks(2830),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 412, DateTimeKind.Utc).AddTicks(2830)
                        },
                        new
                        {
                            RoleId = 8,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 477, DateTimeKind.Utc).AddTicks(110),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 477, DateTimeKind.Utc).AddTicks(110)
                        },
                        new
                        {
                            RoleId = 9,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 542, DateTimeKind.Utc).AddTicks(1980),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 542, DateTimeKind.Utc).AddTicks(1980)
                        },
                        new
                        {
                            RoleId = 10,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 607, DateTimeKind.Utc).AddTicks(6300),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 607, DateTimeKind.Utc).AddTicks(6300)
                        },
                        new
                        {
                            RoleId = 11,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 671, DateTimeKind.Utc).AddTicks(8440),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 671, DateTimeKind.Utc).AddTicks(8440)
                        },
                        new
                        {
                            RoleId = 12,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 736, DateTimeKind.Utc).AddTicks(6630),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 736, DateTimeKind.Utc).AddTicks(6630)
                        },
                        new
                        {
                            RoleId = 13,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 803, DateTimeKind.Utc).AddTicks(8210),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 803, DateTimeKind.Utc).AddTicks(8210)
                        },
                        new
                        {
                            RoleId = 14,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 871, DateTimeKind.Utc).AddTicks(8490),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 871, DateTimeKind.Utc).AddTicks(8490)
                        },
                        new
                        {
                            RoleId = 15,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 942, DateTimeKind.Utc).AddTicks(8500),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 942, DateTimeKind.Utc).AddTicks(8500)
                        },
                        new
                        {
                            RoleId = 16,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 13, DateTimeKind.Utc).AddTicks(8520),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 13, DateTimeKind.Utc).AddTicks(8520)
                        },
                        new
                        {
                            RoleId = 17,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 82, DateTimeKind.Utc).AddTicks(410),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 82, DateTimeKind.Utc).AddTicks(410)
                        },
                        new
                        {
                            RoleId = 18,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 152, DateTimeKind.Utc).AddTicks(4070),
                            RoleType = 0,
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 152, DateTimeKind.Utc).AddTicks(4070)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 957, DateTimeKind.Utc).AddTicks(9030),
                            Email = "ole.gerlach@email.com",
                            FirstName = "Ole",
                            LastName = "Gerlach",
                            Password = "AQAAAAIAAYagAAAAEFRW7f4APJR2wirXSe1QDlv/yqswzbiiTldFe3TE+Tq+lwmYYG2jhdWUf8PVZF0lsQ==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 34, 957, DateTimeKind.Utc).AddTicks(9030)
                        },
                        new
                        {
                            UserId = 2,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 22, DateTimeKind.Utc).AddTicks(5680),
                            Email = "tianna.auer@email.com",
                            FirstName = "Tianna",
                            LastName = "Auer",
                            Password = "AQAAAAIAAYagAAAAEHaKHnnl/QZ006XLCBFlCl8/EO5wscRXRqF5wU8mj1hOoKtVrJi6K1YFE1YgwSyAWQ==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 22, DateTimeKind.Utc).AddTicks(5680)
                        },
                        new
                        {
                            UserId = 3,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 87, DateTimeKind.Utc).AddTicks(2630),
                            Email = "abraham.reinger@email.com",
                            FirstName = "Abraham",
                            LastName = "Reinger",
                            Password = "AQAAAAIAAYagAAAAEH+69RcAoFUxHTmLA99AY1WXuqj/8L8/Sg4tXv/deS9carq3LxF9Wb5+Qn+jzyXJRA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 87, DateTimeKind.Utc).AddTicks(2630)
                        },
                        new
                        {
                            UserId = 4,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 154, DateTimeKind.Utc).AddTicks(6180),
                            Email = "antonietta.weimann@email.com",
                            FirstName = "Antonietta",
                            LastName = "Weimann",
                            Password = "AQAAAAIAAYagAAAAEKqtYXir+0672KBdJY0HdIG27B9yh/7lXkKN+2yZS3WzYuz+ZPmtkXP84bsG3guwQQ==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 154, DateTimeKind.Utc).AddTicks(6180)
                        },
                        new
                        {
                            UserId = 5,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 220, DateTimeKind.Utc).AddTicks(2810),
                            Email = "creola.luettgen@email.com",
                            FirstName = "Creola",
                            LastName = "Luettgen",
                            Password = "AQAAAAIAAYagAAAAEMgNEAlKcGEqyZ9piN4iBQ4pYcPonzyzFkk6YGln+MzIk6d5QofvqzUAv/9q4DDcCA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 220, DateTimeKind.Utc).AddTicks(2810)
                        },
                        new
                        {
                            UserId = 6,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 284, DateTimeKind.Utc).AddTicks(1840),
                            Email = "darrick.ankunding@email.com",
                            FirstName = "Darrick",
                            LastName = "Ankunding",
                            Password = "AQAAAAIAAYagAAAAEMEzSEl8vI0DZexH1cpZIaq4EivxyBoD/nvEzkjMrUqqBw1ZoEZOaS4UduP2Y+0btQ==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 284, DateTimeKind.Utc).AddTicks(1840)
                        },
                        new
                        {
                            UserId = 7,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 349, DateTimeKind.Utc).AddTicks(3850),
                            Email = "marcelino.spencer@email.com",
                            FirstName = "Marcelino",
                            LastName = "Spencer",
                            Password = "AQAAAAIAAYagAAAAEAJKiMxKLlCXd4NfLJv5/L/8VZTpHKnFHEcKcIxsuLyQPbSL127URefd6eMIowstzA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 349, DateTimeKind.Utc).AddTicks(3850)
                        },
                        new
                        {
                            UserId = 8,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 414, DateTimeKind.Utc).AddTicks(2150),
                            Email = "penelope.grady@email.com",
                            FirstName = "Penelope",
                            LastName = "Grady",
                            Password = "AQAAAAIAAYagAAAAEOUq6MYwPytaN+ztZ9B1j9PnhQdupze6qkGGQiuPjXFxYlZM/JbkXU741/464mIrYA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 414, DateTimeKind.Utc).AddTicks(2150)
                        },
                        new
                        {
                            UserId = 9,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 478, DateTimeKind.Utc).AddTicks(9760),
                            Email = "sandy.christiansen@email.com",
                            FirstName = "Sandy",
                            LastName = "Christiansen",
                            Password = "AQAAAAIAAYagAAAAEBqxGbd1CU1zbRpvSzaJTrDKNSk3vUzmu9hslLu1wmkpD0jIANtnHY5MTAExKvEK5A==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 478, DateTimeKind.Utc).AddTicks(9760)
                        },
                        new
                        {
                            UserId = 10,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 545, DateTimeKind.Utc).AddTicks(2910),
                            Email = "gerry.morar@email.com",
                            FirstName = "Gerry",
                            LastName = "Morar",
                            Password = "AQAAAAIAAYagAAAAENCY78d0hUlweeASiiX46w4aSU3RhDzTCXv/Ki5wOHrJNolfF5E01OEtr7q8462iag==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 545, DateTimeKind.Utc).AddTicks(2910)
                        },
                        new
                        {
                            UserId = 11,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 609, DateTimeKind.Utc).AddTicks(7430),
                            Email = "louvenia.herzog@email.com",
                            FirstName = "Louvenia",
                            LastName = "Herzog",
                            Password = "AQAAAAIAAYagAAAAECyp6FYwAL4HbBKEl7YXKi5vuMyDzCtH5Hkxt2AgGn5UgenXSY35XmqEr/NwufISRQ==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 609, DateTimeKind.Utc).AddTicks(7430)
                        },
                        new
                        {
                            UserId = 12,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 673, DateTimeKind.Utc).AddTicks(8580),
                            Email = "luciano.emard@email.com",
                            FirstName = "Luciano",
                            LastName = "Emard",
                            Password = "AQAAAAIAAYagAAAAEOhOEtwuFpw8KJyxYJyE1RyTPGqG7fnaJvgwuP5bqh1cFPvXQ9iJlsWxGEVdras5JQ==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 673, DateTimeKind.Utc).AddTicks(8580)
                        },
                        new
                        {
                            UserId = 13,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 738, DateTimeKind.Utc).AddTicks(5840),
                            Email = "keeley.marquardt@email.com",
                            FirstName = "Keeley",
                            LastName = "Marquardt",
                            Password = "AQAAAAIAAYagAAAAEJNGY1sUX5VFkuwU57UAVr05TUF2M9i5oQqkMD5aDqMoWvwnFupSCca0Q9xTccK6tg==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 738, DateTimeKind.Utc).AddTicks(5840)
                        },
                        new
                        {
                            UserId = 14,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 805, DateTimeKind.Utc).AddTicks(9330),
                            Email = "lincoln.cartwright@email.com",
                            FirstName = "Lincoln",
                            LastName = "Cartwright",
                            Password = "AQAAAAIAAYagAAAAEEc9+2cAnC4tazMH/fKQG7eUn6CZs2leluf4B1MtNGCVVOQmYiqO6aEkqrYCpJjGJg==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 805, DateTimeKind.Utc).AddTicks(9330)
                        },
                        new
                        {
                            UserId = 15,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 873, DateTimeKind.Utc).AddTicks(9550),
                            Email = "earl.kohler@email.com",
                            FirstName = "Earl",
                            LastName = "Kohler",
                            Password = "AQAAAAIAAYagAAAAEDeucBNkcFJ3AotIuNYR13a6rrwLUCr6QPP39UN0IHYxpyL4dCm0OGOmM7+Y3su/eg==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 873, DateTimeKind.Utc).AddTicks(9550)
                        },
                        new
                        {
                            UserId = 16,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 945, DateTimeKind.Utc).AddTicks(6290),
                            Email = "brad.goyette@email.com",
                            FirstName = "Brad",
                            LastName = "Goyette",
                            Password = "AQAAAAIAAYagAAAAEGbfbRuuY8fC6xWAsYt+FIWjQJlN5VwJRO1RcZKBB1NMm41JV3kUGtYpYj4RYJiRmA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 945, DateTimeKind.Utc).AddTicks(6290)
                        },
                        new
                        {
                            UserId = 17,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 17, DateTimeKind.Utc).AddTicks(4900),
                            Email = "nellie.ryan@email.com",
                            FirstName = "Nellie",
                            LastName = "Ryan",
                            Password = "AQAAAAIAAYagAAAAEJ5Nsjv2mAsdDEq1JeORXtmiLGU+XsKto7cBAYA5qGWXDSI/MjFq//GJwQGgjwz1EA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 17, DateTimeKind.Utc).AddTicks(4900)
                        },
                        new
                        {
                            UserId = 18,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 83, DateTimeKind.Utc).AddTicks(9870),
                            Email = "lyla.mclaughlin@email.com",
                            FirstName = "Lyla",
                            LastName = "McLaughlin",
                            Password = "AQAAAAIAAYagAAAAEBqwb6G766nFpTu2UQj6exlJWRQBAPrudb4XpY3jk3eCZSKCT4N9uR7i8NJdV00LFA==",
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 83, DateTimeKind.Utc).AddTicks(9870)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.UserInstrument", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("InstrumentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "InstrumentId");

                    b.HasIndex("InstrumentId");

                    b.ToTable("UserInstruments");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            InstrumentId = 1,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 20, DateTimeKind.Utc).AddTicks(6610),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 20, DateTimeKind.Utc).AddTicks(6610)
                        },
                        new
                        {
                            UserId = 2,
                            InstrumentId = 2,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 85, DateTimeKind.Utc).AddTicks(2710),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 85, DateTimeKind.Utc).AddTicks(2710)
                        },
                        new
                        {
                            UserId = 3,
                            InstrumentId = 3,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 151, DateTimeKind.Utc).AddTicks(7310),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 151, DateTimeKind.Utc).AddTicks(7310)
                        },
                        new
                        {
                            UserId = 4,
                            InstrumentId = 4,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 218, DateTimeKind.Utc).AddTicks(220),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 218, DateTimeKind.Utc).AddTicks(220)
                        },
                        new
                        {
                            UserId = 5,
                            InstrumentId = 5,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 282, DateTimeKind.Utc).AddTicks(2090),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 282, DateTimeKind.Utc).AddTicks(2090)
                        },
                        new
                        {
                            UserId = 6,
                            InstrumentId = 6,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 347, DateTimeKind.Utc).AddTicks(1920),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 347, DateTimeKind.Utc).AddTicks(1920)
                        },
                        new
                        {
                            UserId = 7,
                            InstrumentId = 7,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 412, DateTimeKind.Utc).AddTicks(2830),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 412, DateTimeKind.Utc).AddTicks(2830)
                        },
                        new
                        {
                            UserId = 8,
                            InstrumentId = 8,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 477, DateTimeKind.Utc).AddTicks(110),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 477, DateTimeKind.Utc).AddTicks(110)
                        },
                        new
                        {
                            UserId = 9,
                            InstrumentId = 9,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 542, DateTimeKind.Utc).AddTicks(1990),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 542, DateTimeKind.Utc).AddTicks(1990)
                        },
                        new
                        {
                            UserId = 10,
                            InstrumentId = 11,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 607, DateTimeKind.Utc).AddTicks(6300),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 607, DateTimeKind.Utc).AddTicks(6300)
                        },
                        new
                        {
                            UserId = 11,
                            InstrumentId = 12,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 671, DateTimeKind.Utc).AddTicks(8450),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 671, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            UserId = 12,
                            InstrumentId = 13,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 736, DateTimeKind.Utc).AddTicks(6640),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 736, DateTimeKind.Utc).AddTicks(6640)
                        },
                        new
                        {
                            UserId = 13,
                            InstrumentId = 14,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 803, DateTimeKind.Utc).AddTicks(8220),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 803, DateTimeKind.Utc).AddTicks(8220)
                        },
                        new
                        {
                            UserId = 14,
                            InstrumentId = 15,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 871, DateTimeKind.Utc).AddTicks(8500),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 871, DateTimeKind.Utc).AddTicks(8500)
                        },
                        new
                        {
                            UserId = 15,
                            InstrumentId = 17,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 942, DateTimeKind.Utc).AddTicks(8520),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 942, DateTimeKind.Utc).AddTicks(8520)
                        },
                        new
                        {
                            UserId = 16,
                            InstrumentId = 18,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 13, DateTimeKind.Utc).AddTicks(8530),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 13, DateTimeKind.Utc).AddTicks(8530)
                        },
                        new
                        {
                            UserId = 17,
                            InstrumentId = 19,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 82, DateTimeKind.Utc).AddTicks(410),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 82, DateTimeKind.Utc).AddTicks(410)
                        },
                        new
                        {
                            UserId = 18,
                            InstrumentId = 20,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 152, DateTimeKind.Utc).AddTicks(4080),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 152, DateTimeKind.Utc).AddTicks(4080)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 20, DateTimeKind.Utc).AddTicks(6610),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 20, DateTimeKind.Utc).AddTicks(6610)
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 2,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 85, DateTimeKind.Utc).AddTicks(2710),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 85, DateTimeKind.Utc).AddTicks(2710)
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 3,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 151, DateTimeKind.Utc).AddTicks(7300),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 151, DateTimeKind.Utc).AddTicks(7310)
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 4,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 218, DateTimeKind.Utc).AddTicks(220),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 218, DateTimeKind.Utc).AddTicks(220)
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 5,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 282, DateTimeKind.Utc).AddTicks(2030),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 282, DateTimeKind.Utc).AddTicks(2030)
                        },
                        new
                        {
                            UserId = 6,
                            RoleId = 6,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 347, DateTimeKind.Utc).AddTicks(1910),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 347, DateTimeKind.Utc).AddTicks(1920)
                        },
                        new
                        {
                            UserId = 7,
                            RoleId = 7,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 412, DateTimeKind.Utc).AddTicks(2830),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 412, DateTimeKind.Utc).AddTicks(2830)
                        },
                        new
                        {
                            UserId = 8,
                            RoleId = 8,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 477, DateTimeKind.Utc).AddTicks(110),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 477, DateTimeKind.Utc).AddTicks(110)
                        },
                        new
                        {
                            UserId = 9,
                            RoleId = 9,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 542, DateTimeKind.Utc).AddTicks(1980),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 542, DateTimeKind.Utc).AddTicks(1980)
                        },
                        new
                        {
                            UserId = 10,
                            RoleId = 10,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 607, DateTimeKind.Utc).AddTicks(6300),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 607, DateTimeKind.Utc).AddTicks(6300)
                        },
                        new
                        {
                            UserId = 11,
                            RoleId = 11,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 671, DateTimeKind.Utc).AddTicks(8450),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 671, DateTimeKind.Utc).AddTicks(8450)
                        },
                        new
                        {
                            UserId = 12,
                            RoleId = 12,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 736, DateTimeKind.Utc).AddTicks(6630),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 736, DateTimeKind.Utc).AddTicks(6630)
                        },
                        new
                        {
                            UserId = 13,
                            RoleId = 13,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 803, DateTimeKind.Utc).AddTicks(8210),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 803, DateTimeKind.Utc).AddTicks(8210)
                        },
                        new
                        {
                            UserId = 14,
                            RoleId = 14,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 871, DateTimeKind.Utc).AddTicks(8500),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 871, DateTimeKind.Utc).AddTicks(8500)
                        },
                        new
                        {
                            UserId = 15,
                            RoleId = 15,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 942, DateTimeKind.Utc).AddTicks(8510),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 35, 942, DateTimeKind.Utc).AddTicks(8510)
                        },
                        new
                        {
                            UserId = 16,
                            RoleId = 16,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 13, DateTimeKind.Utc).AddTicks(8520),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 13, DateTimeKind.Utc).AddTicks(8520)
                        },
                        new
                        {
                            UserId = 17,
                            RoleId = 17,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 82, DateTimeKind.Utc).AddTicks(410),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 82, DateTimeKind.Utc).AddTicks(410)
                        },
                        new
                        {
                            UserId = 18,
                            RoleId = 18,
                            CreatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 152, DateTimeKind.Utc).AddTicks(4080),
                            UpdatedAt = new DateTime(2023, 10, 11, 15, 48, 36, 152, DateTimeKind.Utc).AddTicks(4080)
                        });
                });

            modelBuilder.Entity("TeamFive.Models.Lesson", b =>
                {
                    b.HasOne("TeamFive.Models.Instrument", "Instrument")
                        .WithMany("Lessons")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "Student")
                        .WithMany("AttendedLessons")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "Teacher")
                        .WithMany("TaughtLessons")
                        .HasForeignKey("TeacherId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("Student");

                    b.Navigation("Teacher");
                });

            modelBuilder.Entity("TeamFive.Models.RefreshToken", b =>
                {
                    b.HasOne("TeamFive.Models.User", "User")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamFive.Models.UserInstrument", b =>
                {
                    b.HasOne("TeamFive.Models.Instrument", "Instrument")
                        .WithMany("UserInstruments")
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "User")
                        .WithMany("UserInstruments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Instrument");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamFive.Models.UserRole", b =>
                {
                    b.HasOne("TeamFive.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TeamFive.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TeamFive.Models.Instrument", b =>
                {
                    b.Navigation("Lessons");

                    b.Navigation("UserInstruments");
                });

            modelBuilder.Entity("TeamFive.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("TeamFive.Models.User", b =>
                {
                    b.Navigation("AttendedLessons");

                    b.Navigation("RefreshTokens");

                    b.Navigation("TaughtLessons");

                    b.Navigation("UserInstruments");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
